// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1hvhzts6WqNDo1PqnZWjdtZs5c3V_N7Y',
    appId: '1:384358357105:web:d249167d15dc47765ca3d0',
    messagingSenderId: '384358357105',
    projectId: 'prakflutterfirebase-e05c3',
    authDomain: 'prakflutterfirebase-e05c3.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-e05c3.appspot.com',
    measurementId: 'G-176FWJZYHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoRUSpHdbOHb61NlCYJYm5f0yiuY1Ro20',
    appId: '1:384358357105:android:8d53f3a5534351a45ca3d0',
    messagingSenderId: '384358357105',
    projectId: 'prakflutterfirebase-e05c3',
    storageBucket: 'prakflutterfirebase-e05c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDSleey207CPIQGAFNxvg316RgHijqaL4',
    appId: '1:384358357105:ios:7ea01d88948dd3a05ca3d0',
    messagingSenderId: '384358357105',
    projectId: 'prakflutterfirebase-e05c3',
    storageBucket: 'prakflutterfirebase-e05c3.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDSleey207CPIQGAFNxvg316RgHijqaL4',
    appId: '1:384358357105:ios:7ea01d88948dd3a05ca3d0',
    messagingSenderId: '384358357105',
    projectId: 'prakflutterfirebase-e05c3',
    storageBucket: 'prakflutterfirebase-e05c3.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1hvhzts6WqNDo1PqnZWjdtZs5c3V_N7Y',
    appId: '1:384358357105:web:5e76818975c5f8195ca3d0',
    messagingSenderId: '384358357105',
    projectId: 'prakflutterfirebase-e05c3',
    authDomain: 'prakflutterfirebase-e05c3.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-e05c3.appspot.com',
    measurementId: 'G-WJ78XJW9XD',
  );
}
